### ISSUE TITLE
??

### ISSUE THREAD

**Issue by RenderBr** [imnagarajan/BlackPrizes#2]
didn't even bother to update the readme... xd

**Comment by imnagarajan** [comment]
> didn't even bother to update the readme... xd

Yes because it's your plugin do I want to change it

**Comment by imnagarajan** [comment]
> didn't even bother to update the readme... xd

I'll change now @RenderBr

**Comment by RenderBr** [comment]
> > didn't even bother to update the readme... xd
> 
> I'll change now @RenderBr

yes because changing one singular piece of text is what i wanted you to do.

i'm more so confused why you decided to copy the plugin line for line, whilst changing the name instead of doing what any normal person would do and simply fork it.

**Comment by imnagarajan** [comment]
> > > didn't even bother to update the readme... xd
> > 
> > 
> > I'll change now @RenderBr
> 
> yes because changing one singular piece of text is what i wanted you to do.
> 
> i'm more so confused why you decided to copy the plugin line for line, whilst changing the name instead of doing what any normal person would do and simply fork it.

I didn't know

**Comment by imnagarajan** [comment]
About fork

**Comment by imnagarajan** [comment]
> About fork

Ok done @RenderBr
